from routes.blueprints.q_crud import *
from routes.blueprints.answer_form import *
from routes.blueprints.details import *
from routes.blueprints.choices import *
from routes.blueprints.export import *
from routes.blueprints.load import *
from routes.blueprints.save import *
from routes.blueprints.export import *
from routes.blueprints.other import *
from routes.blueprints.shutdown import *
from routes.blueprints.qg_crud import *